name: Tests

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.md'

jobs:

  tests:

    strategy:
      matrix:
        buildconfig: [ Release ]

    runs-on: windows-latest

    env:
      project: src\GenesysCloudOAuthWebView.Tests\GenesysCloudOAuthWebView.Tests.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install nbgv
      uses: dotnet/nbgv@v0.4.0

    - name: Test
      run: dotnet test $env:project -c $env:config
      env:
        config: ${{ matrix.buildconfig }}